In [1]:
import numpy as np
import json
import pandas as pd
import pickle
import matplotlib.pyplot as plt

In [2]:
fn = 'checkpoint_norm.pkl'

In [3]:
with open(fn, 'rb') as f:
    g = pickle.load(f)

In [4]:
data = g.edge_mat
mapping = g.node_idx_map

In [82]:
idx = np.where((data != 0).sum(axis=1) == 0)[0]

In [85]:
(data != 0)

array([[ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       ...,
       [False, False, False, ...,  True,  True,  True],
       [False, False, False, ...,  True,  True,  True],
       [False, False, False, ...,  True,  True,  True]])

In [83]:
idx

array([   9,   10,   11, ..., 8054, 8055, 8056])

In [92]:
(data[9] == 0).all()

True

In [93]:
count = 0
for i in idx:
    if (data[i] ==0).all() == False:
#         print('found nonzero elements')
        count += 1
    
print(count)

0


In [70]:
test = data[4556:4570]
test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [71]:
test.shape

(14, 8231)

In [72]:
np.any(0)

False

In [79]:
(test != 0).sum(axis=1)

array([  2, 282,  57, 247, 618, 560, 365, 241, 459, 474, 424,   3, 461,
       211])

In [81]:
np.where((test != 0).sum(axis=1) == 0)[0]#.all(axis=0))

array([], dtype=int64)

In [69]:
test[4734]

16.0

In [56]:
# find the idx of nodes that have 0 mobility for all row entries
idxs = np.where(test.any(axis=1))[0]

In [57]:
idxs

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [30]:
test[4]

array([0., 0., 0., 0.])